# This is the configuration file for generating synthetic user news data.


n_samples: 20000   # Number of synthetic data samples to generate

news_types:        # List of possible news categories
  - Politics
  - Sports
  - Technology
  - Health
  - Entertainment
  - Business
  - Science
  - Environment
  - Education
  - World
  - Economy
  - Travel
  - Food
  - Lifestyle
  - Culture
  - Opinion
  - Crime
  - Weather
  - Real Estate
  - Automotive
  - others

summary_length:                   # Summary length configuration. Represents number of words
  min_summary_length: 200         # Minimum length of the summary
  max_summary_length: 2500        # Maximum length of the summary

time_spent_per_summary_len:       # Time spent reading news configuration. the time is in seconds
  multiplier: 0.1                 # Used to scale summary length to estimate time spent
  std_dev: 6                      # Standard deviation for time spent (used in normal distribution)
  min_value: 15                   # Minimum time spent in seconds

clicked:                          # full_article_button_clicked configuration
  threshold_s: 6                  # Threshold of time spent in article in seconds to determine if the button was clicked
  probs_below: [0.6, 0.4]         # [not clicked, clicked], if time spent is below threshold
  probs_above: [0.3, 0.7]         # [not clicked, clicked], if time spent is above threshold

like_dislike:                     # like_dislike configuration
  coded_values:                   # Hard-coded values for like/dislike
    - condition: 
        engagement_max: 0.3            
        engagement_min: 0.1             
        clicked: 1
      probability: [0.2,0.3,0.5]  # Probabilities for dislike, neutral, like

    - condition:
        engagement_max: 0.3
        engagement_min: 0.1
        clicked: 0
      probability: [0.2,0.5,0.3]

    - condition:
        engagement_max: 0.1
        engagement_min: 0.001
        clicked: 1
      probability: [0.3,0.4,0.3]

    - condition:
        engagement_max: 0.1
        engagement_min: 0.001
        clicked: 0
      probability: [0.6,0.3,0.1]

  
  like_dislike_rules_default_value: [0.2,0.6,0.2]  # Default probabilities for dislike, neutral, like for custom rules


score_coded_values:                    
  - condition:
      engagement_max: 0.3                   # Maximum engagement threshold for the rule, time_spent / summary_length
      engagement_min: 0.11                  # Minimun engagement threshold for the rule, time_spent / summary_length
      clicked_value: 1                      # Button clicked
      like_dislike_value: 1                 # Like
    output :
      mean: 9.5                             # Mean score for the rule
      std: 0.5                              # Standard deviation for the rule

  - condition:
      engagement_max: 0.3
      engagement_min: 0.11
      clicked_value: 1
      like_dislike_value: 0
    output :
      mean: 8.0
      std: 0.5

  - condition:
      engagement_max: 0.3
      engagement_min: 0.11
      clicked_value: 1
      like_dislike_value: -1 
    output :
      mean: 6.0
      std: 0.5

  - condition:
      engagement_max: 0.3
      engagement_min: 0.11
      clicked_value: 0                      
      like_dislike_value: 1
    output :
      mean: 8.5
      std: 0.5

  - condition:
      engagement_max: 0.3
      engagement_min: 0.11
      clicked_value: 0
      like_dislike_value: 0
    output :
      mean: 7.0
      std: 0.5
  - condition:
      engagement_max: 0.3
      engagement_min: 0.11
      clicked_value: 0
      like_dislike_value: -1
    output :
      mean: 5.0
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 1
      like_dislike_value: 1
    output :
      mean: 8.5
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 1
      like_dislike_value: 0
    output :
      mean: 7.0
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 1
      like_dislike_value: -1
    output :
      mean: 5.0
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 0
      like_dislike_value: 1
    output :
      mean: 7.5
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 0
      like_dislike_value: 0
    output :
      mean: 6.0
      std: 0.5

  - condition:
      engagement_max: 0.11
      engagement_min: 0.1
      clicked_value: 0
      like_dislike_value: -1
    output :
      mean: 4.0
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 1
      like_dislike_value: 1
    output :
      mean: 7.5
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 1
      like_dislike_value: 0
    output :
      mean: 6.0
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 1
      like_dislike_value: -1
    output :
      mean: 4.0
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 0
      like_dislike_value: 1
    output :
      mean: 6.5
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 0
      like_dislike_value: 0
    output :
      mean: 5.0
      std: 0.5

  - condition:
      engagement_max: 0.1
      engagement_min: 0.095
      clicked_value: 0
      like_dislike_value: -1
    output :
      mean: 3.0
      std: 0.5

  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 1
      like_dislike_value: 1
    output :
      mean: 6.5
      std: 0.6

  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 1
      like_dislike_value: 0
    output :
      mean: 5.0
      std: 0.6

  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 1
      like_dislike_value: -1
    output :
      mean: 3.0
      std: 0.6

  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 0
      like_dislike_value: 1
    output :
      mean: 5.5
      std: 0.6

  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 0
      like_dislike_value: 0
    output :
      mean: 4.0
      std: 0.6
  
  - condition:
      engagement_max: 0.095
      engagement_min: 0.085
      clicked_value: 0
      like_dislike_value: -1
    output :
      mean: 2.0
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 1
      like_dislike_value: 1
    output :
      mean: 5.5
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 1
      like_dislike_value: 0
    output :
      mean: 4.0
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 1
      like_dislike_value: -1
    output :
      mean: 2.0
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 0
      like_dislike_value: 1
    output :
      mean: 4.5
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 0
      like_dislike_value: 0
    output :
      mean: 3.0
      std: 0.6

  - condition:
      engagement_max: 0.085
      engagement_min: 0.001
      clicked_value: 0
      like_dislike_value: -1
    output :
      mean: 1.0
      std: 0.6

score_rules_default_value:           # Default values for scoring rules
  mean: 5.0                          # Default mean score                  
  std: 1.0                           # Default standard deviation

dataset_destination: Autogen\dataset\user_news_data.csv        # Destination of the dataset in .csv